using System.Globalization;
using System.Net;
using System.Text;
using NetControl.Core.Persistence;

namespace NetControl.Core.Reporting;

/// <summary>
/// The commissioning record as one self-contained HTML page - the startup record a customer is handed
/// at the end of a job. It prints to PDF from any browser, and it needs nothing but the file it is in.
///
/// <para><b>It reads the project file and nothing else.</b> No live state, no adapter, no clock but
/// the one stamping when it was generated - so a report regenerated from the same project file on a
/// different laptop next year says exactly the same thing. Every time in it is UTC for the same
/// reason: a record that changes with the time zone of whoever opens it is not one record.</para>
///
/// <para>Every device's state is the record's: Verified only where the last finished operation was a
/// readback that matched (see <see cref="CommissioningRecord"/>), served only where an
/// <c>Assignment</c> row says so. Nothing in the report is inferred that the record does not say.</para>
///
/// <para>All text from the file is HTML-encoded on the way out. A project file is a SQLite database
/// somebody may have edited by hand, and a note containing markup must come out as the text it is.</para>
/// </summary>
public static class CommissioningReport
{
    private const string TimeFormat = "yyyy-MM-dd HH:mm:ss 'UTC'";

    /// <summary>Builds the page.</summary>
    /// <param name="project">The project to report on. Read only.</param>
    /// <param name="generatedUtc">When, for the header.</param>
    /// <param name="generatedBy">The build generating it - "NetControl 0.8.0+abc1234" - for the header.</param>
    public static string BuildHtml(ProjectStore project, DateTimeOffset generatedUtc, string? generatedBy = null)
    {
        ArgumentNullException.ThrowIfNull(project);

        IReadOnlyList<DeviceRecord> devices = project.Devices.All();
        IReadOnlyList<EventRecord> events = project.Events.All();
        IReadOnlyList<ScanRunRecord> scans = project.Scans.Runs();
        IReadOnlyDictionary<long, DeviceCommissioning> outcomes = CommissioningRecord.LastOutcomes(events);
        Dictionary<long, AssignmentRecord> lastServed = LastServed(project, devices);

        var html = new StringBuilder(64 * 1024);

        Head(html, project);

        html.Append("<header>");
        html.Append(CultureInfo.InvariantCulture, $"<h1>{E(project.Project.Name)}</h1>");
        html.Append("<p class=\"sub\">Commissioning record</p>");
        html.Append("<dl class=\"meta\">");
        Meta(html, "Project file", project.IsInMemory ? "not saved to a file" : project.FilePath);
        Meta(html, "Project created", Time(project.Project.CreatedUtc));
        Meta(html, "Report generated", Time(generatedUtc));
        Meta(html, "Generated by", generatedBy ?? "NetControl");
        Meta(html, "Builds that wrote to it", BuildsIn(events));
        html.Append("</dl></header>");

        Summary(html, devices, outcomes, lastServed, events);
        DeviceTable(html, devices, outcomes, lastServed);
        Attention(html, events, devices);
        Commissioning(html, events, devices);
        ScanTable(html, scans);
        EventLog(html, events, devices);

        html.Append("<footer>Generated from the project file's append-only event log. Every row in it was written ");
        html.Append("as the operation happened, and the file refuses any change to it.</footer>");
        html.Append("</body></html>");

        return html.ToString();
    }

    private static void Head(StringBuilder html, ProjectStore project)
    {
        html.Append("<!DOCTYPE html><html lang=\"en\"><head><meta charset=\"utf-8\">");
        html.Append("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">");
        html.Append(CultureInfo.InvariantCulture, $"<title>{E(project.Project.Name)} - commissioning record</title>");
        html.Append("<style>");
        html.Append("""
            :root { --ink:#1d2329; --muted:#5d6670; --line:#d5dade; --soft:#f3f5f7; --good:#1f7a43;
                    --warn:#9a6200; --bad:#b3261e; --accent:#2b5da8; }
            * { box-sizing:border-box; }
            body { font:14px/1.45 "Segoe UI", system-ui, -apple-system, sans-serif; color:var(--ink);
                   margin:0 auto; max-width:1180px; padding:28px 24px 40px; background:#fff; }
            h1 { font-size:26px; margin:0; } h2 { font-size:17px; margin:30px 0 8px; padding-bottom:4px;
                   border-bottom:2px solid var(--ink); }
            .sub { margin:2px 0 14px; color:var(--muted); text-transform:uppercase; letter-spacing:.08em;
                   font-size:12px; font-weight:600; }
            dl.meta { display:grid; grid-template-columns:max-content 1fr; gap:3px 18px; margin:0; font-size:13px; }
            dl.meta dt { color:var(--muted); } dl.meta dd { margin:0; word-break:break-all; }
            .tiles { display:grid; grid-template-columns:repeat(auto-fit,minmax(150px,1fr)); gap:10px; margin-top:22px; }
            .tile { border:1px solid var(--line); border-radius:6px; padding:10px 12px; }
            .tile b { display:block; font-size:24px; } .tile span { color:var(--muted); font-size:12px; }
            table { border-collapse:collapse; width:100%; font-size:12.5px; }
            th, td { text-align:left; vertical-align:top; padding:5px 7px; border-bottom:1px solid var(--line); }
            th { background:var(--soft); font-weight:600; white-space:nowrap; }
            tr { break-inside:avoid; }
            .mono { font-family:Consolas, "Cascadia Mono", monospace; white-space:nowrap; }
            .muted { color:var(--muted); }
            .pill { display:inline-block; padding:1px 7px; border-radius:9px; font-size:11.5px; font-weight:600;
                    white-space:nowrap; border:1px solid currentColor; }
            .verified { color:var(--good); } .served, .info { color:var(--accent); }
            .notverified, .warn { color:var(--warn); } .error { color:var(--bad); } .planned { color:var(--muted); }
            .none { color:var(--muted); font-style:italic; }
            footer { margin-top:34px; color:var(--muted); font-size:12px; }
            @media print { body { padding:0; max-width:none; } h2 { break-after:avoid; } }
            """);
        html.Append("</style></head><body>");
    }

    private static void Summary(
        StringBuilder html,
        IReadOnlyList<DeviceRecord> devices,
        IReadOnlyDictionary<long, DeviceCommissioning> outcomes,
        Dictionary<long, AssignmentRecord> lastServed,
        IReadOnlyList<EventRecord> events)
    {
        int verified = devices.Count(d => State(d, outcomes, lastServed) == "Verified");
        int notVerified = devices.Count(d => State(d, outcomes, lastServed) == "Not verified");
        int served = lastServed.Count;
        int addressed = devices.Count(d => d.PlannedIp is not null);
        int warnings = events.Count(e => e.Severity == EventSeverity.Warn);
        int errors = events.Count(e => e.Severity == EventSeverity.Error);

        html.Append("<div class=\"tiles\">");
        Tile(html, devices.Count, "devices in the plan");
        Tile(html, addressed, "with a planned address");
        Tile(html, served, "served an address");
        Tile(html, verified, "verified static", verified == addressed && addressed > 0 ? "verified" : null);
        Tile(html, notVerified, "last attempt not verified", notVerified > 0 ? "notverified" : null);
        Tile(html, warnings + errors, "warnings and errors in the log", errors > 0 ? "error" : warnings > 0 ? "warn" : null);
        html.Append("</div>");
    }

    private static void DeviceTable(
        StringBuilder html,
        IReadOnlyList<DeviceRecord> devices,
        IReadOnlyDictionary<long, DeviceCommissioning> outcomes,
        Dictionary<long, AssignmentRecord> lastServed)
    {
        html.Append("<h2>Devices</h2>");

        if (devices.Count == 0)
        {
            html.Append("<p class=\"none\">The plan is empty.</p>");
            return;
        }

        html.Append("<table><thead><tr><th>MAC</th><th>Device</th><th>Panel</th><th>Planned address</th>");
        html.Append("<th>Vendor</th><th>State</th><th>Served</th><th>Last write</th><th>Notes</th></tr></thead><tbody>");

        foreach (DeviceRecord device in devices.OrderBy(d => Numeric(d.PlannedIp)).ThenBy(d => d.Mac.ToString()))
        {
            string state = State(device, outcomes, lastServed);
            outcomes.TryGetValue(device.Id, out DeviceCommissioning? last);
            lastServed.TryGetValue(device.Id, out AssignmentRecord? served);

            string address = device.PlannedIp is null
                ? "<span class=\"none\">none</span>"
                : $"<span class=\"mono\">{E(device.PlannedIp)}</span>"
                    + (device.PlannedMask is null ? string.Empty : $"<br><span class=\"mono muted\">mask {E(device.PlannedMask)}</span>")
                    + (device.PlannedGateway is null ? string.Empty : $"<br><span class=\"mono muted\">gw {E(device.PlannedGateway)}</span>");

            string stateClass = state.Replace(" ", string.Empty, StringComparison.Ordinal).ToLowerInvariant();

            string servedCell = served is null
                ? "<span class=\"none\">no</span>"
                : $"<span class=\"mono\">{E(served.ServedIp)}</span><br>"
                    + $"<span class=\"muted\">{E(Time(served.ServedUtc))} on {E(served.NicName)}</span>";

            string lastCell = last is null
                ? "<span class=\"none\">nothing written</span>"
                : $"{E(last.Message)}<br><span class=\"muted\">{E(Time(last.Utc))}</span>";

            html.Append("<tr>");
            html.Append(CultureInfo.InvariantCulture, $"<td class=\"mono\">{E(device.Mac)}</td>");
            html.Append(CultureInfo.InvariantCulture, $"<td>{E(device.DisplayName)}</td>");
            html.Append(CultureInfo.InvariantCulture, $"<td>{E(device.PanelRef)}</td>");
            html.Append(CultureInfo.InvariantCulture, $"<td>{address}</td>");
            html.Append(CultureInfo.InvariantCulture, $"<td>{E(device.Vendor)}</td>");
            html.Append(CultureInfo.InvariantCulture, $"<td><span class=\"pill {stateClass}\">{E(state)}</span></td>");
            html.Append(CultureInfo.InvariantCulture, $"<td>{servedCell}</td>");
            html.Append(CultureInfo.InvariantCulture, $"<td>{lastCell}</td>");
            html.Append(CultureInfo.InvariantCulture, $"<td>{E(device.Notes)}</td>");
            html.Append("</tr>");
        }

        html.Append("</tbody></table>");
    }

    private static void Attention(StringBuilder html, IReadOnlyList<EventRecord> events, IReadOnlyList<DeviceRecord> devices)
    {
        List<EventRecord> flagged = [.. events.Where(e => e.Severity != EventSeverity.Info)];

        html.Append("<h2>Needs attention</h2>");

        if (flagged.Count == 0)
        {
            html.Append("<p class=\"none\">Nothing in the record was graded a warning or an error.</p>");
            return;
        }

        html.Append("<p class=\"muted\">Every warning and error in the record, oldest first.</p>");
        EventRows(html, flagged, devices);
    }

    private static void Commissioning(StringBuilder html, IReadOnlyList<EventRecord> events, IReadOnlyList<DeviceRecord> devices)
    {
        List<EventRecord> cip = [.. events.Where(e => e.Category == EventCategory.Cip)];

        html.Append("<h2>Writes to devices</h2>");

        if (cip.Count == 0)
        {
            html.Append("<p class=\"none\">Nothing was written to any device over EtherNet/IP.</p>");
            return;
        }

        html.Append("<p class=\"muted\">Every EtherNet/IP step - Set static, hand-backs, diagnostics reads - as it ");
        html.Append("happened, including what was sent and what came back.</p>");
        EventRows(html, cip, devices);
    }

    private static void ScanTable(StringBuilder html, IReadOnlyList<ScanRunRecord> scans)
    {
        html.Append("<h2>Scans</h2>");

        if (scans.Count == 0)
        {
            html.Append("<p class=\"none\">No scan was run in this project.</p>");
            return;
        }

        html.Append("<table><thead><tr><th>When</th><th>Adapter</th><th>Subnet</th><th>Devices answered</th>");
        html.Append("</tr></thead><tbody>");

        foreach (ScanRunRecord scan in scans.OrderBy(s => s.Utc).ThenBy(s => s.Id))
        {
            string subnet = scan.TryGetSubnet(out Ipv4Subnet s) ? s.ToString() : string.Empty;

            html.Append(CultureInfo.InvariantCulture,
                $"<tr><td class=\"mono\">{E(Time(scan.Utc))}</td><td>{E(scan.NicName)}</td>"
                + $"<td class=\"mono\">{E(subnet)}</td><td>{scan.Answered}</td></tr>");
        }

        html.Append("</tbody></table>");
    }

    private static void EventLog(StringBuilder html, IReadOnlyList<EventRecord> events, IReadOnlyList<DeviceRecord> devices)
    {
        html.Append("<h2>Event log</h2>");

        if (events.Count == 0)
        {
            html.Append("<p class=\"none\">The record is empty.</p>");
            return;
        }

        html.Append(CultureInfo.InvariantCulture,
            $"<p class=\"muted\">All {events.Count} row(s), oldest first, exactly as recorded.</p>");
        EventRows(html, events, devices);
    }

    private static void EventRows(StringBuilder html, IEnumerable<EventRecord> rows, IReadOnlyList<DeviceRecord> devices)
    {
        Dictionary<long, DeviceRecord> byId = devices.ToDictionary(d => d.Id);

        html.Append("<table><thead><tr><th>When</th><th></th><th>Category</th><th>About</th><th>What happened</th>");
        html.Append("</tr></thead><tbody>");

        foreach (EventRecord row in rows.OrderBy(e => e.Id))
        {
            string about = row.DeviceId is { } id && byId.TryGetValue(id, out DeviceRecord? device)
                ? (device.DisplayName ?? device.Mac.ToString())
                : row.Target ?? string.Empty;

            string severity = row.Severity switch
            {
                EventSeverity.Error => "error",
                EventSeverity.Warn => "warn",
                _ => "info",
            };

            html.Append(CultureInfo.InvariantCulture,
                $"<tr><td class=\"mono\">{E(Time(row.Utc))}</td>"
                + $"<td><span class=\"pill {severity}\">{severity}</span></td>"
                + $"<td>{E(SqlCategory(row.Category))}</td><td>{E(about)}</td><td>{E(row.Message)}</td></tr>");
        }

        html.Append("</tbody></table>");
    }

    /// <summary>The state the record supports, in the words the grid uses.</summary>
    private static string State(
        DeviceRecord device,
        IReadOnlyDictionary<long, DeviceCommissioning> outcomes,
        Dictionary<long, AssignmentRecord> lastServed)
    {
        if (outcomes.TryGetValue(device.Id, out DeviceCommissioning? last))
        {
            switch (last.Outcome)
            {
                case CommissioningOutcome.Verified
                    when device.PlannedIp is { } planned
                        && (last.Readback is null || last.Readback.StartsWith($"ip={planned} ", StringComparison.Ordinal)):
                    return "Verified";

                case CommissioningOutcome.NotVerified:
                    return "Not verified";

                case CommissioningOutcome.HandedBack:
                    return "Handed back";
            }
        }

        return lastServed.ContainsKey(device.Id) ? "Served" : "Planned";
    }

    private static Dictionary<long, AssignmentRecord> LastServed(ProjectStore project, IReadOnlyList<DeviceRecord> devices)
    {
        var served = new Dictionary<long, AssignmentRecord>();

        foreach (DeviceRecord device in devices)
        {
            // Newest first, so the first is the latest.
            if (project.Assignments.ForDevice(device.Id) is [var latest, ..])
            {
                served[device.Id] = latest;
            }
        }

        return served;
    }

    /// <summary>The distinct builds that stamped the file - "Opened by NetControl 0.8.0." rows.</summary>
    private static string BuildsIn(IReadOnlyList<EventRecord> events)
    {
        string[] builds = [.. events
            .Where(e => e.Category == EventCategory.App
                && e.Message.StartsWith("Opened by ", StringComparison.Ordinal))
            .Select(e => e.Message["Opened by ".Length..].TrimEnd('.'))
            .Distinct(StringComparer.Ordinal)];

        return builds.Length == 0 ? "not recorded" : string.Join(", ", builds);
    }

    private static void Meta(StringBuilder html, string term, string value) =>
        html.Append(CultureInfo.InvariantCulture, $"<dt>{E(term)}</dt><dd>{E(value)}</dd>");

    private static void Tile(StringBuilder html, int value, string label, string? tone = null) =>
        html.Append(CultureInfo.InvariantCulture,
            $"<div class=\"tile\"><b class=\"{tone ?? string.Empty}\">{value}</b><span>{E(label)}</span></div>");

    private static string Time(DateTimeOffset value) =>
        value.ToUniversalTime().ToString(TimeFormat, CultureInfo.InvariantCulture);

    private static string SqlCategory(EventCategory category) => category.ToString().ToLowerInvariant();

    private static string E(object? value) => WebUtility.HtmlEncode(value?.ToString() ?? string.Empty);

    private static uint Numeric(IPAddress? address)
    {
        if (address is null)
        {
            return uint.MaxValue;
        }

        byte[] bytes = address.GetAddressBytes();
        return bytes.Length == 4
            ? ((uint)bytes[0] << 24) | ((uint)bytes[1] << 16) | ((uint)bytes[2] << 8) | bytes[3]
            : uint.MaxValue;
    }
}
